[package]
name = "tsp-grasp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.3", features = ["derive"] }
petgraph = "0.6.4"
rand = "0.8.5"
tspf = "0.3.1"
